### ISSUE TITLE
error when ourdated client connect

### ISSUE THREAD

**Issue by dutchy1001** [Fireflies/BungeeEssentials#26] opened 2016-03-05 12:27 UTC
When a client connects with 1.8 on a 1.9 server i get this error in the bungee console.
http://pastebin.com/SvffTcx7
I don't think it's a major issue but more an annoying one.

**Comment by pantherman594** [comment] 2016-03-05 22:25
I'm unable to reproduce this error. Are there any errors when the player joins, or only when the player quits?

**Comment by dutchy1001** [comment] 2016-03-05 23:50
I'm not so sure it's a client with 1.8. I tried a few versions of 1.8 myself and cant reproduce it either. I just get the "normal" kick message with no error in console. The player in the log (uSkyblock) was using a 1.9 client he told me.
Scrolling back I did found a good few more errors, not sure if related. You can see the whole log [here](https://mega.nz/#!u0kESKKL!kq8fWClKVGIrl3U_qT1rWu1klSsfNxCS5fKMMrYFCC4) (be aware its a long one lol)

I wont be supriced if there is something wrong on my side after seeing the errors, but you will tell me that then.

**Comment by pantherman594** [comment] 2016-03-20 03:26
Should be fixed with https://github.com/PantherMan594/BungeeEssentials/commit/28494ecedbb8955960da27a6ed1dcedb8ba7676c

**Closed as completed by pantherman594** 2016-03-20 03:26 UTC
Labels: bug
